---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-core
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/workshop-cluster/infra/operators/kyverno/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kyverno-base
  timeout: 10m0s
  wait: true
